// Copyright 2026, Evan Palmer
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

#pragma once

#include <memory>

#include "geometry_msgs/msg/twist_with_covariance_stamped.hpp"
#include "libnucleus/client.hpp"
#include "marine_acoustic_msgs/msg/dvl.hpp"
#include "rclcpp_components/register_node_macro.hpp"
#include "rclcpp_lifecycle/lifecycle_node.hpp"
#include "nav_msgs/msg/odometry.hpp"

// auto-generated by generate_parameter_library
#include <nucleus_driver/nucleus_driver_parameters.hpp>

namespace nucleus::ros
{

using CallbackReturn = rclcpp_lifecycle::node_interfaces::LifecycleNodeInterface::CallbackReturn;

class NucleusDriver : public rclcpp_lifecycle::LifecycleNode
{
public:
  explicit NucleusDriver(const rclcpp::NodeOptions & options = rclcpp::NodeOptions());

  auto on_configure(const rclcpp_lifecycle::State & previous_state) -> CallbackReturn override;

  auto on_activate(const rclcpp_lifecycle::State & previous_state) -> CallbackReturn override;

private:
  std::unique_ptr<NucleusClient> client_;

  std::shared_ptr<nucleus_driver::ParamListener> param_listener_;
  nucleus_driver::Params params_;

  // Declare the DVL messages to avoid re-initializing it every time it gets published
  marine_acoustic_msgs::msg::Dvl dvl_msg_;
  geometry_msgs::msg::TwistWithCovarianceStamped twist_msg_;  // used by state estimators
  nav_msgs::msg::Odometry odom_msg_;  // used by state estimators

  std::shared_ptr<rclcpp::Publisher<marine_acoustic_msgs::msg::Dvl>> dvl_pub_;
  std::shared_ptr<rclcpp::Publisher<geometry_msgs::msg::TwistWithCovarianceStamped>> twist_pub_;
  std::shared_ptr<rclcpp::Publisher<nav_msgs::msg::Odometry>> odom_pub_;
};

}  // namespace nucleus::ros

RCLCPP_COMPONENTS_REGISTER_NODE(nucleus::ros::NucleusDriver)
